# Generated by Django 5.2.15 on 2026-07-06 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_alter_user_role_client_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans_client', to='scanner.client'),
        ),
    ]
