# Generated by Django 5.2.15 on 2026-07-07 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_scan_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='VulnerabiliteManuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vuln', models.CharField(choices=[('idor', 'IDOR - Insecure Direct Object Reference'), ('lfi', 'LFI - Local File Inclusion'), ('xss', 'XSS - Cross-Site Scripting'), ('sqli', 'SQL Injection'), ('csrf', 'CSRF'), ('broken_auth', 'Broken Authentication'), ('sensitive_data', 'Sensitive Data Exposure'), ('spam', 'Spam / Abus'), ('autre', 'Autre')], default='autre', max_length=30)),
                ('nom', models.CharField(max_length=255)),
                ('impacted_element', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('risk', models.CharField(choices=[('critical', 'Critique'), ('high', 'Élevé'), ('medium', 'Moyen'), ('low', 'Faible')], default='medium', max_length=20)),
                ('cvss_score', models.FloatField(default=0.0)),
                ('cvss_vector', models.CharField(blank=True, max_length=100)),
                ('priorite', models.CharField(blank=True, max_length=50)),
                ('complexite', models.CharField(blank=True, max_length=50)),
                ('technical_business_risks', models.TextField(blank=True)),
                ('recommandation', models.TextField(blank=True)),
                ('proof_of_concept', models.TextField(blank=True)),
                ('references', models.TextField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ajoutee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilites_manuelles', to='scanner.scan')),
            ],
        ),
    ]
